### PR TITLE
fix: misaligned result button

### LINKED ISSUE #2617: Button in Results -> Responses view is misaligned
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
In the Results -> Responses view, there is a "three dots" button next to each submission. The button is not aligned with the headline. Unfortunately the headline has a `margin-bottom` from global headline styles and the button doesn't. So I think it would be a quick fix, to also give the button a `margin-bottom` and `margin-left` of 12px.

```css
.submission-menu {
  margin-bottom: 12px;
  margin-left: 12px;
}
```

**To Reproduce**

1. Open any Form
2. Click on Results
3. Click on the "Responses" toggle/view
4. Look at any response headline

**Expected behavior**
Button should be aligned with the headline.

**Screenshots**

Image

**Nextcloud (please complete the following information):**

- Nextcloud-Version: 30.0.4
- Forms-Version: 5.0.2

**Additional context**

### PR DESCRIPTION
**Pull request by pReya**
closes #2617 

Sorry, this is untested, I don't have a proper Dev setup running here and it would probably take me hours to get it running just to test these two lines of CSS. So I would be thankful if someone could verify that this is working as intended.

The existing class was doubly nested in SCSS, so it didn't work before and came out aus `.submission-head-menu`  (while `.submission-menu` is used in the DOM). I fixed this definition and added the needed margin values for the button to be correctly aligned.

### CODE REVIEW

File: src/components/Results/Submission.vue [hunk 1]
```diff
@@ -138,9 +138,11 @@ export default {
 			font-weight: bold;
 		}
 
-		&-menu {
-			display: inline-block;
-		}
+	}
+	
+	&-menu {
+		margin: 0 0 12px 12px;
```
Comment (Chartman123) [inline src/components/Results/Submission.vue:144]:
```suggestion
		margin: 0 0 12px var(--default-grid-baseline);
```
I think the left margin of 12px is too big. The `var(--default-grid-baseline)` fits much better in my opinion.

**Review by Chartman123 — CHANGES_REQUESTED** [review]
Thank you very much. Just a little adjustment and I think we're good to go and merge it :)

File: src/components/Results/Submission.vue [hunk 2]
```diff
@@ -138,9 +138,11 @@ export default {
 			font-weight: bold;
 		}
 
-		&-menu {
-			display: inline-block;
-		}
+	}
+
```
Comment (Chartman123) [inline src/components/Results/Submission.vue:142]:
```suggestion

```

Wrong indentation

File: src/components/Results/Submission.vue [hunk 3]
```diff
@@ -138,9 +138,11 @@ export default {
 			font-weight: bold;
 		}
 
-		&-menu {
-			display: inline-block;
-		}
+	}
+	
+	&-menu {
```
Comment (Chartman123) [inline src/components/Results/Submission.vue:143]:
```suggestion
	}

	&-menu {
```

Wrong indentation

File: src/components/Results/Submission.vue [hunk 4]
```diff
@@ -138,9 +138,11 @@ export default {
 			font-weight: bold;
 		}
```
Comment (Chartman123) [inline src/components/Results/Submission.vue:140]:
```suggestion
		}
```
Remove extra new line

**Review by Chartman123 — APPROVED** [review]
