### PR TITLE
Fix(migration): Rename primary key of uploaded_files table

### LINKED ISSUE #2648: Error while enabling Forms: Primary index name "id" for table "oc_forms_v2_uploaded_files" collides with the constraint on table "oc_bookmarks".
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Downloaded and trying to enable Forms app. results in error:
```
Primary index name "id" for table "oc_forms_v2_uploaded_files" collides with the constraint on table "oc_bookmarks".
```
**To Reproduce**
Go to **App bundles > Public sector bundle**. For **Forms** app click **Enable**.

**Expected behavior**
Forms app is enabled.

**Nextcloud (please complete the following information):**

- Nextcloud-Version: Nextcloud Hub 9 (30.0.7)
- Forms-Version: 5.0.3

**Desktop (please complete the following information):**

- OS: Debian Sid
- Browser: Firefox
- Version 128.8esr

**Browser log**

Nothing in browser console

### PR DESCRIPTION
**Pull request by Chartman123**
This fixes #2648. It changes the primary key name parameter in the original migration and adds a new migration for existing installations that drops the old primary key and creates a new one with the new name.

Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

### CODE REVIEW

File: lib/Migration/Version040300Date20240523123456.php [hunk 1]
```diff
@@ -59,7 +59,7 @@ public function changeSchema(IOutput $output, Closure $schemaClosure, array $opt
 				'notnull' => false,
 				'comment' => 'unix-timestamp',
 			]);
-			$table->setPrimaryKey(['id'], 'id');
+			$table->setPrimaryKey(['id']);
```
Comment (susnux) [inline lib/Migration/Version040300Date20240523123456.php:62]: we probably should also rename it for existing installations

**Comment by Chartman123** [comment]
For the backport we need to rename the migration to match the corresponding v4 version

**Review by Koc — APPROVED** [review]

File: lib/Migration/Version050004Date20250319180638.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		if ($schema->hasTable('forms_v2_uploaded_files')) {
+			$table = $schema->getTable('forms_v2_uploaded_files');
+			$table->dropPrimaryKey();
+			$table->setPrimaryKey(['id'], 'forms_upload_files_id');
```
Comment (susnux) [inline lib/Migration/Version050004Date20250319180638.php:35]: Or simply no custom key name

Comment (Chartman123) [reply lib/Migration/Version050004Date20250319180638.php:35]: This does not work, because the then chosen default is too long and triggers an error

Comment (susnux) [reply lib/Migration/Version050004Date20250319180638.php:35]: 🙈
