### PR TITLE
fix(Submit): Make `answers` reactive and fix invalid mutation of computed property

### LINKED ISSUE #1780: Checkboxes/Radio buttons don't update in UI if values are loaded from LocalStorage
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Checkboxes/Radio buttons don't update in Submit view if values are loaded from LocalStorage. If on empty form, everything works fine.

**To Reproduce**
1. Fill some values in an empty form including checkbox/radio questions in Submit view
2. Leave form
3. Come back to form in Submit view
4. Click on checkbox/radio options
5. UI doesn't adjust, focus hangs on checkbox/radio, Local Storage gets updated
6. Reload page, see changes in UI

**Expected behavior**
Checkboxes/Radios get updated on click/change

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.3
- Forms-Version: latest main

**Browser log**
```
Nothing in browser log
```

### PR DESCRIPTION
**Pull request by susnux**
* Alternative to resolve #1780 

This fixes the root cause for the question component not updating: Non reactive answers in `Submit`, meaning after assigning a new value to `answers[key]` the watch effect was never triggered and thus the question component was never updated.
So instead use a `onUpdate` method to update the `answers` object in a way that will trigger any watch effect.

Also make `getFormValuesFromLocalStorage` a method instead a computed value. Previously that computed value were assigned a new value which is invalid as computed values should be constant (except for computed setter but this was none).

### CODE REVIEW

**Comment by susnux** [comment]
Works also with "other" answer:

https://github.com/nextcloud/forms/assets/1855448/1943f40b-4cd7-4d66-b452-dda2e37ac2aa

File: src/components/Questions/QuestionMultiple.vue [hunk 1]
```diff
@@ -311,12 +317,10 @@ export default {
 			options.push({
 				id: GenRandomId(),
 				questionId: this.id,
-				text: this.inputValue,
+				text: '',
 				local: true,
 			})
 
-			this.inputValue = ''
-
```
Comment (Chartman123) [inline src/components/Questions/QuestionMultiple.vue:319]: This is needed for the new create view behaviour... I need to get the input from the pseudo input for new options and pass them to the new AnswerInput for the new option

File: src/components/Questions/QuestionMultiple.vue [hunk 2]
```diff
@@ -197,29 +197,21 @@ export default {
...
-				values.push(this.valueOtherAnswer)
+		/**
+		 * Text of the "other" answer field
+		 */
+		otherAnswerText() {
+			if (this.otherAnswer) {
+				return this.otherAnswer.slice(QUESTION_EXTRASETTINGS_OTHER_PREFIX.length)
 			}
+			return ''
+		},
```
Comment (Chartman123) [inline src/components/Questions/QuestionMultiple.vue:208]: This changes the current behaviour: when you unselect the checkbox/radio for the custom answer, the text stays in the input box so that you don't have to re-type the text when you select the option again.

With this change the text gets removed as soon as you unselect the option

Comment (susnux) [reply src/components/Questions/QuestionMultiple.vue:208]: Do we want to keep the old behavior? Would require to cache the input (additional data and watcher)

File: src/components/Questions/QuestionMultiple.vue (hunk 1 above)
Comment (susnux) [reply src/components/Questions/QuestionMultiple.vue:319]: Fixed:

https://github.com/nextcloud/forms/assets/1855448/01fdaeb4-3aeb-410b-aa5f-be185a671546

File: src/components/Questions/QuestionMultiple.vue (hunk 2 above)
Comment (Chartman123) [reply src/components/Questions/QuestionMultiple.vue:209]: If it's not too much effort, I would prefer to keep the old behaviour... Might be an edge use case that someone checks/unchecks the other option but then might be really annoying to always have to re-type the answer.

Comment (susnux) [reply src/components/Questions/QuestionMultiple.vue]: Fixed

**Comment by susnux** [comment]
Fixed the "other" answer cache, see:


https://github.com/nextcloud/forms/assets/1855448/09974ccd-1240-4139-b226-a513ebe94fd8

File: src/components/Questions/QuestionMultiple.vue [hunk 3]
```diff
@@ -61,10 +61,11 @@
 						@keydown.enter.exact.prevent="onKeydownEnter">
 						{{ t('forms', 'Other:') }}
 					</NcCheckboxRadioSwitch>
-					<NcInputField :label="placeholderOtherAnswer"
-						:required="hasRequiredOtherAnswerInput"
-						:value.sync="inputOtherAnswer"
-						class="question__input" />
+					<NcInputField class="question__input"
+						:label="placeholderOtherAnswer"
+						:disabled="otherAnswer === undefined"
```
Comment (Chartman123) [inline src/components/Questions/QuestionMultiple.vue:66]: Is this necessary? With this change you have to first check the checkbox/radio, before you could start to write into the field and that triggered the checked state

Comment (susnux) [reply src/components/Questions/QuestionMultiple.vue:66]: Not really, but it simplifies the code and makes the flow easier as from the control structure the element is disabled when not selected. Meaning the accessibility properties should list it as disabled.

Comment (Chartman123) [reply src/components/Questions/QuestionMultiple.vue:66]: Ok, but from UX perspective I'd prefer the way it is e.g. also handled by Google: type into the input and auto check the correponding radio/checkbox

Comment (susnux) [reply src/components/Questions/QuestionMultiple.vue]: Fixed:

https://github.com/nextcloud/forms/assets/1855448/c43528ae-fd28-457a-9f01-d6badde03f51

**Review by Chartman123 — APPROVED** [review]
