### PR TITLE
fix: Improve compatibility with Windows for uploaded files

### LINKED ISSUE #2409: The Forms folder structure is not sanitized which can lead to synchronization issues when uploading files
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Uploaded files are seemingly saved in a folder structure `Forms/{id of form} - {title of form}/{id of submission}/{id of question} - {title of question}` but the titles do not seem to get trimmed in regards to trailing white spaces, which results in syncing problems (at least on Windows 11 with NTFS).

**To Reproduce**

1. Go to Forms and create a new form
2. Call it `test ` with a trailing whitespace
3. Add a file upload option and call it `test ` as well
4. Upload a file

**Expected behavior**
I expect the fields that are used for filenames to be trimmed in regard to whitespace and maybe also sanitized regarding other invalid characters like `:`

**Screenshots**
Image

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 30.0.2
-   Forms-Version: 4.3.3

**Desktop (please complete the following information):**

-   OS: Windows 11 with NTFS file system
- Nexcloud Desktop v3.14.3

### PR DESCRIPTION
**Pull request by Koc**
Fixes #2409

### CODE REVIEW

File: lib/Service/FormsService.php [hunk 1]
```diff
@@ -44,6 +44,19 @@
  * @psalm-import-type FormsShare from ResponseDefinitions
  */
 class FormsService {
+	private const FILENAME_INVALID_CHARS = [
```
Comment (Chartman123) [inline lib/Service/FormsService.php:47]: Could you move this to the Constants? And how about using the OCP constants and just combining it with the remaining ones?

**Review by Chartman123 — CHANGES_REQUESTED** [review]

File: lib/Service/FormsService.php (hunk 1 above)
Comment (susnux) [reply lib/Service/FormsService.php:47]: Neither of it just use `OCP\Files\IFilenameValidator` and I do not think we should replace them but forbid upload of files containing them.
But also do it in the fronend:

[nextcloud-files validateFilename](https://nextcloud-libraries.github.io/nextcloud-files/functions/index.validateFilename.html)

Comment (Chartman123) [reply lib/Service/FormsService.php:47]: Ok, didn't know about that :) But yes, then I agree, we should already use the validation upon uploading the files in the frontend and the backend, so that we don't have to manipulate the filenames afterwards.

Comment (Chartman123) [reply lib/Service/FormsService.php:47]: But one thing remains: The folder structure is based on the question titles. So if you for example put a `:` in the title of a file question, the corresponding folders can't be sync'ed on Windows devices.

Comment (Koc) [reply lib/Service/FormsService.php]: ok, so I've moved `FILENAME_INVALID_CHARS` into `Constants` class. Regarding other hints:

- combining `OCP\Constants::FILENAME_INVALID_CHARS` + `\OCA\Forms\Constants::FILENAME_INVALID_CHARS` has no sense for me because I've defined invalid chars as an array but global invalid characters defined as string. Array is better here because we don't need call `mb_str_split` all the time
- `IFilenameValidator` - we're already calling `$userFolder->getStorage()->verifyPath($path, $uploadedFile['name']);` during file upload. Is it not enough? Even more, as already mentioned, uploaded file can have correct name, but due to form/question name path can be invalid

Anyway, feel free to force-push any changes into my branch.

Comment (Koc) [reply lib/Service/FormsService.php]: @Chartman123 @susnux mates, can you check one more time?

**Review by Chartman123 — APPROVED** [review]
