### PR TITLE
Fix users & groups sharing

### LINKED ISSUE #19: Does not respect autocomplete settings
**Which Forms version are you running?** (see apps page)
1.0.3
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.8
### Steps to reproduce
1. Uncheck checkbox 'Allow autocomplete username in sharing dialog' under '/settings/admin/sharing'
2. Choose 'Only Shared' under Apps 'Configuration -> Access'
3. start typing to find user to share form with 

### Actual behaviour
Full list of users matching partial input shows

### Expected behaviour
Only on full name match it should show match list

### PR DESCRIPTION
**Pull request by skjnldsv**
- [x] Use files_sharing api
- [x] Use same input as in files sharing sidebar
- [x] Cleanup old files
- [x] Add api sanity checks
- [x] Improve api access data

fix #19

### CODE REVIEW

**Comment by skjnldsv** [comment]
Please not this doesn't add the same layout as server yet!
Will be easier to add after though.
This is about the sharing providers.

Ideally I would like the app to understand that we 'interacted with' xxx when sharing here too.
So it appear in the recommendation app

File: lib/Service/FormsService.php [hunk 1]
```diff
@@ -205,4 +222,39 @@ public function hasUserAccess(int $formId): bool {
...
+				'displayName' => $user->getDisplayName()
+			];
+		}
+		return [];
+	}
+
+	/**
+	 * Format groups access
+	 *
+	 * @param string $userId
```
Comment (jotoeri) [inline lib/Service/FormsService.php:246]: *groupId

File: lib/Service/FormsService.php [hunk 2]
```diff
@@ -205,4 +222,39 @@ public function hasUserAccess(int $formId): bool {
...
 		return false;
 	}
+
+	/**
+	 * Format users access
+	 *
+	 * @param string $userId
+	 * @return array
+	 */
+	private function formatUsers(string $userId): array {
```
Comment (jotoeri) [inline lib/Service/FormsService.php:232]: Can we move these two procedures above getForm? Then we have a block of corresponding procedores above getForm. Makes it easier to find correlated functions...

File: src/components/UserDiv.vue [hunk 3]
```diff
@@ -42,37 +36,19 @@ export default {
 		Avatar,
 	},
 	props: {
-		hideNames: {
-			type: Boolean,
-			default: false,
-		},
-		userId: {
+		id: {
```
Comment (jotoeri) [inline src/components/UserDiv.vue:39]: userId to clarify?

File: lib/Service/FormsService.php [hunk 4]
```diff
@@ -205,4 +222,39 @@ public function hasUserAccess(int $formId): bool {
...
+	 * @param string $userId
+	 * @return array
+	 */
+	private function formatGroups(string $groupId): array {
+		$group  = $this->groupManager->get($groupId);
+		if ($group instanceof IGroup) {
+			return [
+				'id' => $groupId,
+				'displayName' => $group->getDisplayName(),
+				'isGroup' => true
```
Comment (jotoeri) [inline lib/Service/FormsService.php:255]: in UserDiv you used `type=user/group` for this. How about using the same variable here?

File: src/components/UserDiv.vue [hunk 5]
```diff
@@ -82,7 +58,7 @@ export default {
 		computedDisplayName() {
 			let value = this.displayName
 
-			if (this.userId === getCurrentUser().uid) {
+			if (!this.isNoUser && this.userId === getCurrentUser().uid) {
```
Comment (jotoeri) [inline src/components/UserDiv.vue:61]: Inverting to isUser makes it easier to read...

File: src/components/UserDiv.vue [hunk 6]
```diff
@@ -82,7 +58,7 @@ export default {
...
 				value = getCurrentUser().displayName
```
Comment (jotoeri) [inline src/components/UserDiv.vue:62]: loading the display-name for current-user again, doesn't make sense. Would only apply, if the owner shares with himself?!

File: src/components/shareDiv.vue [hunk 7]
```diff
@@ -23,122 +23,155 @@
...
+		isValidQuery() {
+			return this.query && this.query.trim() !== '' && this.query.length > this.minSearchStringLength
+		},
+
+		/**
+		 * Multiseelct options. Recommendations by default,
+		 * direct search when search query is valid.
+		 * @returns {Array}
+		 */
+		options() {
```
Comment (jotoeri) [inline src/components/shareDiv.vue:127]: use `multiselectOptions` as name?

File: src/components/shareDiv.vue [hunk 8]
```diff
@@ -23,122 +23,155 @@
...
-		},
+		/**
+		 * Add a new share and dispatch the change to the parent
+		 * @param {Object} share the new share
+		 */
+		addShare(share) {
+			const users = this.userShares.slice()
+			const groups = this.groupShares.slice()
+			const newShare = {
+				id: share.shareWith,
```
Comment (jotoeri) [inline src/components/shareDiv.vue:162]: `share.userId`?

File: lib/Service/FormsService.php (hunk 2 above)
Comment (skjnldsv) [reply lib/Service/FormsService.php:232]: Of course!

File: src/components/UserDiv.vue (hunk 3 above)
Comment (skjnldsv) [reply src/components/UserDiv.vue:39]: No, it's used for groups as well

File: lib/Service/FormsService.php (hunk 4 above)
Comment (skjnldsv) [reply lib/Service/FormsService.php:255]: After thought, I think we should be as close as the original sharing code, so I'd move to sharingType :)

File: src/components/UserDiv.vue (hunk 5 above)
Comment (skjnldsv) [reply src/components/UserDiv.vue:61]: Definitely! UserDiv is the part that will be removed anyway :p

File: src/components/UserDiv.vue (hunk 6 above)
Comment (skjnldsv) [reply src/components/UserDiv.vue:62]: I mean, this is the olde code, didn't changed anything here :stuck_out_tongue:

File: src/components/shareDiv.vue (hunk 8 above)
Comment (skjnldsv) [reply src/components/shareDiv.vue:162]: Nope, this is the files_sharing code here :)

File: src/components/shareDiv.vue (hunk 7 above)
Comment (skjnldsv) [reply src/components/shareDiv.vue:127]: rather keep the same as the html prop `options`

File: src/components/UserDiv.vue (hunk 6 above)
Comment (skjnldsv) [reply src/components/UserDiv.vue:62]: Ah, no, and it's also because isNoUser is the name of the Avatar prop :)

File: src/components/UserDiv.vue (hunk 3 above)
Comment (jotoeri) [reply src/components/UserDiv.vue:39]: 👍

**Comment by skjnldsv** [comment]
Done! Please update review @jotoeri :)

**Comment by skjnldsv** [comment]
> Looks good, but the state of sharing is not reflected in the dropdown.

We don't show the existing shares in the dropdown :)
Same as we do in sharing

File: lib/Controller/ApiController.php [hunk 9]
```diff
@@ -210,6 +212,21 @@ public function updateForm(int $id, array $keyValuePairs): Http\JSONResponse {
...
 		}
 
+		// Make sure we only store id
+		try {
+			if ($keyValuePairs['access']) {
+				$keyValuePairs['access']['users'] = array_map(function (array $user): string {
+					return $user['id'];
+				}, $keyValuePairs['access']['users']);
+				$keyValuePairs['access']['groups'] = array_map(function (array $group): string {
+					return$group['id'];
```
Comment (jotoeri) [inline lib/Controller/ApiController.php:222]: Typo missing space

Comment (skjnldsv) [reply lib/Controller/ApiController.php]: Dammit ! :grin:

Comment (skjnldsv) [reply lib/Controller/ApiController.php]: Done

File: src/components/shareDiv.vue [hunk 10]
```diff
@@ -147,6 +178,196 @@ export default {
...
+		 */
+		async getSuggestions(search) {
+			this.loading = true
+
+			const shareType = [
+				this.SHARE_TYPES.SHARE_TYPE_USER,
+				this.SHARE_TYPES.SHARE_TYPE_GROUP,
+			]
+
+			const request = await axios.get(generateOcsUrl('apps/files_sharing/api/v1') + 'sharees', {
```
Comment (jotoeri) [inline src/components/shareDiv.vue:206]: One more typo? :D 'sharees'

Comment (jotoeri) [reply src/components/shareDiv.vue:206]: Ok, seems to be inteded. 🤔

**Comment by jancborchardt** [comment]
> > Looks good, but the state of sharing is not reflected in the dropdown.
> 
> We don't show the existing shares in the dropdown :)
> Same as we do in sharing

They do show for me, I can add people multiple times, and they keep showing in the dropdown even if I close and open again.

**Comment by jotoeri** [comment]
Sorry, thought you would have fixed the Group-Thing.

- [ ] The shown active Shares have the popup, showing (Group) on users, but not on Groups.

> They do show for me, I can add people multiple times, and they keep showing in the dropdown even if I close and open again.

This one works for me, i don't see them... 🤔

**Comment by jancborchardt** [comment]
>     * [ ]  The shown active Shares have the popup, showing (Group) on users, but not on Groups.

Can confirm, seems to be inverse logic.


> > They do show for me, I can add people multiple times, and they keep showing in the dropdown even if I close and open again.
> 
> This one works for me, i don't see them... thinking

Still getting this issue after update and cache clear, but we can also just ignore that then if nobody can reproduce. :)

File: src/components/UserDiv.vue [hunk 11]
```diff
@@ -20,79 +20,47 @@
...
-				value = getCurrentUser().displayName
-			} else {
-				if (!this.displayName) {
-					value = this.userId
-				}
-			}
-			if (this.type === 'group') {
-				value = value + ' (' + t('forms', 'Group') + ')'
+			if (this.shareType !== this.SHARE_TYPES.SHARE_TYPE_GROUP) {
+				return `${this.displayName} (${t('forms', 'Group')})`
```
Comment (jancborchardt) [inline src/components/UserDiv.vue:61]: There we have the culprit ;) Will fix

**Comment by jancborchardt** [comment]
Does this actually also fix **Does not respect autocomplete settings #19**? cc @ljo

**Comment by skjnldsv** [comment]
> Does this actually also fix **Does not respect autocomplete settings #19**? cc @ljo

Yes :)

File: src/components/UserDiv.vue (hunk 11 above)
Comment (skjnldsv) [reply src/components/UserDiv.vue:61]: Weird, I thought I pushed it yesterday!
Let me push now

**Comment by jotoeri** [comment]
Ok, so now i found Jan's bug, as well as a new one:
- [ ] The one, that Jan mentioned: When adding a share, but not changing/closing the search, the old search is still open, so the User/Group can be added a second time. So checking the currently selected items in multiselect would be good, but needs also possibility to uncheck again. Maybe add  shares only when changing search or closing the multiselect?
- [ ] Groups can not be deleted.

**Comment by skjnldsv** [comment]
Fixed & pushed @jancborchardt @jotoeri 
Please do another review :)

File: src/components/shareDiv.vue [hunk 12]
```diff
@@ -144,8 +148,8 @@ export default {
 	methods: {
 		removeShare(item) {
 			// Filter out the removed item
-			const users = this.userShares.filter(user => !(user.id === item.id && !item.isGroup))
-			const groups = this.groupShares.filter(group => !(group.id === item.id && item.isGroup))
+			const users = this.userShares.filter(user => user.shareWith !== item.shareWith && user.shareType !== item.shareType)
+			const groups = this.groupShares.filter(group => group.shareWith !== item.shareWith && group.shareType !== item.shareType)
```
Comment (jotoeri) [inline src/components/shareDiv.vue:152]: The old logic was much easier to understand with the inverted brackets. And as it is now, all shares of the same type will be deleted, when deleting one.
I'd say just use the old code, and check for the item type to be the expected one.
```suggestion
			const users = this.userShares.filter(user => !(user.shareWith === item.shareWith && item.shareType === this.SHARE_TYPES.SHARE_TYPE_USER))
			const groups = this.groupShares.filter(group => !(group.shareWith === item.shareWith && item.shareType === this.SHARE_TYPES.SHARE_TYPE_GROUP))
```

Comment (skjnldsv) [reply src/components/shareDiv.vue:152]: > And as it is now, all shares of the same type will be deleted, when deleting one.

Ah, weird! Nice catch!

**Comment by skjnldsv** [comment]
Thanks Jonas! :hugs: 
So I restored the default search query persistance like it was, like it is on the current sidebar sharing. Was a mistake :)
Also fixed the delete of same entries! :rocket:

File: src/components/ShareDiv.vue [hunk 13]
```diff
@@ -144,8 +148,8 @@ export default {
 	methods: {
 		removeShare(item) {
 			// Filter out the removed item
-			const users = this.userShares.filter(user => !(user.id === item.id && !item.isGroup))
-			const groups = this.groupShares.filter(group => !(group.id === item.id && item.isGroup))
+			const users = this.userShares.filter(user => !(user.shareWith === item.shareWith && user.shareType === this.SHARE_TYPES.SHARE_TYPE_USER))
+			const groups = this.groupShares.filter(group => !(group.shareWith === item.shareWith && group.shareType === this.SHARE_TYPES.SHARE_TYPE_GROUP))
```
Comment (jotoeri) [inline src/components/ShareDiv.vue:152]: Ahhhrgh, i think you want to check the item-share type here, no? A user in userShares is already of that type. 😭

Comment (skjnldsv) [reply src/components/ShareDiv.vue:152]: Dammit :crying_cat_face:

Comment (skjnldsv) [reply src/components/ShareDiv.vue]: Jesus, this day needs to end! :sweat:

**Comment by jancborchardt** [comment]
Haha just tested and wanted to merge too ;) Works nicely now!
