### PR TITLE
fix: subtraction in access_enum

### LINKED ISSUE #2492: Database error when running migration 050000Date20241005173955
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. upgrade our daily instance
2. see error

### Expected behaviour
migration should work

### Actual behaviour
```
$ ./occ app:enable forms
Database error when running migration 050000Date20241005173955 for app forms
An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "3" does not exist
LINE 1: ..."access_enum" = "access_enum - 3" WHERE "access_enum" >= "3"
```

### Server configuration
daily LTD server with PostGres DB
If you need more info, please ping me on chat

### PR DESCRIPTION
**Pull request by Chartman123**
This fixes #2492

### CODE REVIEW

File: lib/Migration/Version050000Date20241005173955.php [hunk 1]
```diff
@@ -31,7 +32,10 @@ public function postSchemaChange(IOutput $output, Closure $schemaClosure, array
 		$qbUpdate = $this->db->getQueryBuilder();
 
 		$qbUpdate->update('forms_v2_forms')
-			->set('access_enum', 'access_enum - 3')
+			->set('access_enum', $qbUpdate->func()->subtract(
+				'access_enum',
+				$qbUpdate->createNamedParameter(3, IQueryBuilder::PARAM_INT)
+			))
 			->where($qbUpdate->expr()->gte('access_enum', '3'))
```
Comment (nickvergessen) [inline lib/Migration/Version050000Date20241005173955.php:39]: Column 3 also does not exist. Make it a placeholder as well

Comment (Chartman123) [reply lib/Migration/Version050000Date20241005173955.php:39]: You mean in line 39?

**Review by nickvergessen — APPROVED** [review]
