### PR TITLE
fix: Make form editable with keyboard

### LINKED ISSUE #416: Impossible to edit questions/answers with keyboard only after initial writing
1. Some a questions with some answers
2. Now don’t use your mouse anymore
3. Using the `Tab` key, try navigating using just your keyboard and edit the existing questions.

It’s not possible as you can not focus the titles or answers, and focusing them does not change it to editing mode.

@jotoeri @skjnldsv any idea how we can trigger that? We can for sure put `tabindex="0"` on each of the question and answer elements, but it needs to then trigger a switch to the edit view.

### PR DESCRIPTION
**Pull request by Chartman123**
This fixes #416 by always showing the edit mode for all fields in Edit/Create view

grafik

To-Do:
- [x] Fix tabbing from multilple choice questions to next question. Probably due to switching between normal Input and AnswerInput.vue (also tracked in #1256)
- [x] Focus after adding question not in title
- [x] emit onInput event after creating a new option only works after first input

### CODE REVIEW

**Comment by Chartman123** [comment]
@susnux @jotoeri While reviewing, please especially have a closer look at my second and third commit. They make the code work the way I wanted, but I'm not sure if there weren't better solutions :)

File: src/components/Questions/AnswerInput.vue [hunk 1]
```diff
@@ -15,7 +15,8 @@
 			dir="auto"
 			@input="onInput"
 			@keydown.delete="deleteEntry"
-			@keydown.enter.prevent="addNewEntry">
+			@keydown.enter.prevent="addNewEntry"
+			@focusout="leaveField">
```
Comment (susnux) [inline src/components/Questions/AnswerInput.vue:19]: I think we do not need this, besides proxying a native HTML event with its HTML name seems to be not a good idea, this is not needed because `focusout` bubbles and therefor we can catch it on the parent without proxying.

**Review by susnux — COMMENTED** [review]
Code looks good, one comment.
But it seems that adding new options on pressing enter is broken now

File: src/components/Questions/AnswerInput.vue (hunk 1 above)
Comment (Chartman123) [reply src/components/Questions/AnswerInput.vue:19]: @susnux I think I only added this as it didn't work with just the `@focusout` in the QuestionDropdown\Multiple.vue

**Comment by Chartman123** [comment]
> But it seems that adding new options on pressing enter is broken now

@susnux Yes, thats true. I will have another look at this...

Do you have an idea how I can fix the problem that new options will only be added to the database when you have at least more than one input events on a new option field? I couldn't find any working solution myself by now...

File: src/components/Questions/AnswerInput.vue (hunk 1 above)
Comment (Chartman123) [reply src/components/Questions/AnswerInput.vue:19]: @susnux I just checked it again, without the @focusout here and then the emit in leaveField the checkValidOptions in QuestionDropdown isn't triggered at all. But Enter/Delete start working again...

**Review by susnux — APPROVED** [review]

File: src/components/Questions/QuestionDropdown.vue [hunk 2]
```diff
@@ -56,17 +56,18 @@
 				:max-option-length="maxStringLengths.optionText"
 				@add="addNewEntry"
 				@delete="deleteOption"
-				@update:answer="updateAnswer" />
+				@update:answer="updateAnswer"
+				@focusout="checkValidOption" />
```
Comment (susnux) [inline src/components/Questions/QuestionDropdown.vue:60]: Should it not be `@tabbed-out`?

Comment (Chartman123) [reply src/components/Questions/QuestionDropdown.vue:60]: Sure, did you add it only to Multiple in your commit? I didn't have a closer look :-/

File: src/components/Questions/QuestionMultiple.vue [hunk 3]
```diff
@@ -252,16 +252,18 @@ export default {
 			return this.areNoneChecked
 		},
 
-		/**
-		 * Remove any empty options when leaving an option
-		 */
```
Comment (susnux) [inline src/components/Questions/QuestionMultiple.vue]: why removing the doc block?

File: src/components/Questions/QuestionMultiple.vue [hunk 4]
```diff
@@ -252,16 +252,18 @@ export default {
...
+					return false
+				}
+				return true
+			})
+
 			// update parent
-			if (options.length !== this.options.length) {
-				this.updateOptions(options)
-			}
+			this.updateOptions(options)
```
Comment (susnux) [inline src/components/Questions/QuestionMultiple.vue:266]: Ah I see the delete was doing more than updating :see_no_evil: 

But the `this.updateOptions(options)` is not needed as it is part of `deleteOption` function, so the same will be emitted twice. So I think we can simplify to:
```js
// When leaving edit mode, filter and delete empty options
this.options.forEach(option => {
	if (!option.text) {
		this.deleteOption(option.id)
	}
})
```

**Review by susnux — APPROVED** [review]
Works but one comment

File: src/components/Questions/QuestionMultiple.vue (hunk 3 above)
Comment (Chartman123) [reply src/components/Questions/QuestionMultiple.vue]: This was not intended...
