### PR TITLE
Fix dropdown submission insert

### LINKED ISSUE #519: Answers for dropdown questions are lost
**Describe the bug**
The answers for the dropdown questions are not registered, and "no response" is shown in results page for all submissions.

**To Reproduce**
1. create a form with a dropdown item
2. answer it
3. go to results
4. see n (100%): no answer

**Expected behavior**
answers are registred

**Screenshots**
image

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.5
- Forms-Version: git master

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox 
 - Version 78

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #519

### CODE REVIEW

File: lib/Controller/ApiController.php [hunk 1]
```diff
@@ -725,7 +726,11 @@ public function insertSubmission(int $formId, array $answers): Http\JSONResponse
 			}
 
 			foreach ($answerArray as $answer) {
-				if ($question['type'] === 'multiple' || $question['type'] === 'multiple_unique') {
+				// Are we using answer ids as values
+				if ($question['type'] === 'multiple'
+					|| $question['type'] === 'multiple_unique'
+					|| $question['type'] === 'dropdown') {
```
Comment (skjnldsv) [inline lib/Controller/ApiController.php:732]: @jotoeri would be nice to have those coming from something like a const somewhere instead of being hardcoded there? :)
What do you think?

**Comment by jancborchardt** [comment]
@c-cesar this fixes the issue you reported, could you give this a review? Thanks! :)

File: lib/Controller/ApiController.php (hunk 1 above)
Comment (jotoeri) [reply lib/Controller/ApiController.php:732]: Urgh, sure, yes 👍
