### PR TITLE
Fix: only show confirmation dialog for active forms

### LINKED ISSUE #2503: Leaving a closed form triggers warning
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When you leave a form that was closed manually and that still has some data in the local storage, you will see the message that asks if you really want to leave the current form. There's no way to reset the form and clear the local storage for the user directly.

**To Reproduce**

1. Go to form and fill in something in view mode
2. Manually close it in the settings
3. Navigate to another form
4. See warning

**Expected behavior**
No warning

**Nextcloud (please complete the following information):**

- Nextcloud-Version: [e.g. 19.0.0] 31.0.0-beta4
- Forms-Version: [e.g. 2.0.0-beta4] 5.0.0-alpha.0

**Browser log**

```
TypeError: this.form.questions is undefined

triggered in validQuestions in Submit.vue:313
```

### PR DESCRIPTION
**Pull request by Chartman123**
This fixes #2503 by checking if the form is active

### CODE REVIEW

File: src/views/Submit.vue [hunk 1]
```diff
@@ -600,18 +600,44 @@ export default {
 		 * Methods for catching unwanted unload events
 		 */
 		beforeWindowUnload(e) {
-			if (!(this.submitForm || Object.keys(this.answers).length === 0)) {
+			if (
+				!this.isArchived &&
+				!this.isClosed &&
+				!this.isExpired &&
```
Comment (susnux) [inline src/views/Submit.vue:606]: Maybe make it a computed `isActive` ^^

**Review by susnux — APPROVED** [review]

File: src/views/Submit.vue (hunk 1 above)
Comment (Chartman123) [reply src/views/Submit.vue:606]: I already thought about that, too. Would improve readability.
